/* BaseJqServiceHttpBindingProxy.h
   Generated by gSOAP 2.8.10 from BaseInterface.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef BaseJqServiceHttpBindingProxy_H
#define BaseJqServiceHttpBindingProxy_H
#include "BaseH.h"
class JqServiceHttpBinding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'JqServiceHttpBinding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	JqServiceHttpBinding()
	{ soap = soap_new(); endpoint = "http://localhost:80"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns", "http://haibogroup.com.cn", NULL, NULL},
	{"ns1", "http://servlet.manage.haibo.com", NULL, NULL},
	{"nsCXF", "http://servlet.webservice.skynet.botech.com/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~JqServiceHttpBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'getData' of service 'JqServiceHttpBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getData(_ns1__getData *ns1__getData, _ns1__getDataResponse *ns1__getDataResponse) { return soap ? soap_call___ns1__getData(soap, endpoint, NULL, ns1__getData, ns1__getDataResponse) : SOAP_EOM; };
};
#endif
